export enum NombresEventosTomaAsistenciaDePersonalSS01 {
  SALUDAME = "SALUDAME",
  RESPUESTA_SALUDO = "RESPUESTA_SALUDO",
  UNIRME_A_SALA_DE_TOMA_DE_ASISTENCIA_DE_PERSONAL = "UNIRME_A_SALA_DE_TOMA_DE_ASISTENCIA_DE_PERSONAL",
  UNIRME_A_SALA_DE_TOMA_DE_ASISTENCIA_DE_UN_AULA_DE_SECUNDARIA = "UNIRME_A_SALA_DE_TOMA_DE_ASISTENCIA_DE_UN_AULA_DE_SECUNDARIA",
  UNIRME_A_SALA_DE_TOMA_DE_ASISTENCIA_DE_UN_AULA_DE_PRIMARIA = "UNIRME_A_SALA_DE_TOMA_DE_ASISTENCIA_DE_UN_AULA_DE_PRIMARIA"
}

